export const ACTION_TYPES = {
    ADD_AUCTION: 'ADD_AUCTION',
    READ_AUCTIONS: 'READ_ACTIONS',
    SET_AUCTION_FACTORY: 'SET_AUCTION_FACTORY',
    GET_AUCTION: 'GET_AUCTION',
    SETUP_ENV: 'SETUP_ENV',
    BID: 'BID',
    END_AUCTION: 'END_AUCTION',
    ERROR: 'ERROR'
};